name: chipseq-automation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.28.0
  - bioconductor-biobase=2.42.0
  - bioconductor-biocgenerics=0.28.0
  - bioconductor-biocparallel=1.16.6
  - bioconductor-chipseeker=1.18.0
  - bioconductor-genomicfeatures=1.34.1
  - bioconductor-genomicranges=1.34.0
  - bioconductor-rtracklayer=1.42.1
  - bowtie2=2.3.5
  - deeptools=3.2.1
  - fastqc=0.11.8
  - macs2=2.1.2
  - python=2.7.15
  - r-base=3.5.1
  - r-getopt=1.20.3
  - r-tidyverse=1.2.1
  - samtools=1.9
  - sra-tools=2.9.1_1
